app:
  name: ecommerce
  version: 1.0.0

server:
  timeout: 5
  port: 5000
  prefork: true

database:
  mariadb:
    host: localhost
    port: 3306
    user: root
    password: admin
    dbname: ecommerce
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_idle_time: 5
    conn_max_lifetime: 60

jwt:
  secret_key: oq283781979nx*(&*!(&*!BUITIUTUQTYW^!&!*!T&^!(@&)@_@Mouowiuiuw8279ntuqwq687168687))
  expires_at: 7
